export default {
  async fetch(request) {
    const { pathname } = new URL(request.url);

    // Función para generar ID simple
    const generateId = () => Math.random().toString(36).slice(2, 9);

    // Tus imágenes con el mismo formato, sin necesidad de modificar cada una
    const imagesData = [
      { id: generateId(), url: "https://i.redd.it/b45dxk0xvq8d1.png", width: null, height: null },
  { id: generateId(), url: "https://statics.memondo.com/p/99/ccs/2025/05/CC_2818345_b3c7daa776a443eda8d67aa8f0354763_meme_otros_soy_un_incomprendido_1.jpg", width: null, height: null },
  { id: generateId(), url: "https://statics.memondo.com/p/99/ccs/2025/05/CC_2818247_018715dc48554c3d83424844503b4513_otros_la_esperanza_es_lo_ultimo_que_se_pierde_1.jpg", width: null, height: null },
  { id: generateId(), url: "https://statics.memondo.com/p/99/ccs/2025/05/CC_2817852_a56bd848b5164818ad555ed0785ef363_meme_otros_bien_de_camuflaje.jpg", width: null, height: null },
  { id: generateId(), url: "https://statics.memondo.com/p/99/ccs/2025/05/CC_2817863_e3c98f0b227a4431aa6de2164a05e65c_meme_otros_adorable_accidente.jpg", width: null, height: null },
  { id: generateId(), url: "https://statics.memondo.com/p/99/ccs/2025/05/CC_2818186_760531510625435ba85b7ca4db09da3c_otros_animales_yendo_al_zoo.jpg", width: null, height: null },
  { id: generateId(), url: "https://statics.memondo.com/p/99/ccs/2025/05/CC_2818310_ced991691ada4717a3619a55ddefe4c5_meme_otros_dia_de_pierna_y_nuca.jpg", width: null, height: null },
  { id: generateId(), url: "https://statics.memondo.com/p/99/ccs/2025/05/CC_2817924_2bd5eb0ec3024b9491a6ccbf516be173_meme_otros_todo_negocio_tiene_sus_comienzos.jpg", width: null, height: null },
  { id: generateId(), url: "https://statics.memondo.com/p/99/ccs/2025/05/CC_2818136_3c2ecee0a833496d9822d3d9e6602819_otros_se_han_ido_ya.jpg", width: null, height: null },
  { id: generateId(), url: "https://statics.memondo.com/p/99/ccs/2025/05/CC_2818060_b85cda456f17428292f5d449c48e144b_meme_otros_a_esa_gente_que_le_pasa.jpg", width: null, height: null },
  { id: generateId(), url: "https://statics.memondo.com/p/99/ccs/2025/05/CC_2818118_c38d37d1f0ab4371b53f6f58bd3f96f8_otros_no_hombre_no_43.jpg", width: null, height: null },
  { id: generateId(), url: "https://statics.memondo.com/p/99/ccs/2025/05/CC_2818323_8f8f6376e0634531a45d4b85e0825f48_meme_otros_hasta_aqui_llegue.jpg", width: null, height: null },
  { id: generateId(), url: "https://statics.memondo.com/p/99/ccs/2025/05/CC_2818284_fc18f9df5e544efe8beb4951c9e9a783_meme_otros_no_valieron_para_nada.jpg", width: null, height: null },
  { id: generateId(), url: "https://statics.memondo.com/p/99/ccs/2025/05/CC_2818264_bcda15b088fb4b40b47cb2808595fb31_meme_otros_princesos_disney.jpg", width: null, height: null },
  { id: generateId(), url: "https://statics.memondo.com/p/99/ccs/2025/05/CC_2818253_323f3ab0580f424c92b411058e971f70_meme_otros_mario_jugaba_con_nuestras_mentes.jpg", width: null, height: null },
  { id: generateId(), url: "https://statics.memondo.com/p/99/ccs/2025/05/CC_2818236_18a41b7b5f56476fbf62b1bf9a57c2a8_otros_no_voy_a_ser_yo_quien_le_refresque_la_memoria.jpg", width: null, height: null },
  { id: generateId(), url: "https://statics.memondo.com/p/99/ccs/2025/05/CC_2818277_d6a82d2b54d4454fba3e9460468ebfde_meme_otros_hay_quien_esclaviza_a_chatgpt.jpg", width: null, height: null },
  { id: generateId(), url: "https://statics.memondo.com/p/99/ccs/2025/05/CC_2818043_97ec2e6f89a0457ba8348992b00ed339_meme_otros_jugando_a_imaginar.jpg", width: null, height: null },
  { id: generateId(), url: "https://statics.memondo.com/p/99/ccs/2025/05/CC_2818043_97ec2e6f89a0457ba8348992b00ed339_meme_otros_jugando_a_imaginar.jpg", width: null, height: null },
  { id: generateId(), url: "https://statics.memondo.com/p/99/ccs/2025/05/CC_2818182_b48d404824e94035b41e22c0e8ce71b4_otros_la_sorpresa_se_la_llevaron_sus_amigos.jpg", width: null, height: null },
  { id: generateId(), url: "https://www.elbutanero.com/content/uploads/images/October2022/IMG-20221019-WA0002.jpg", width: null, height: null },
  { id: generateId(), url: "https://www.elbutanero.com/content/uploads/images/October2022/IMG-20221028-WA0003.jpg", width: null, height: null },
  { id: generateId(), url: "https://www.elbutanero.com/content/uploads/images/October2022/IMG-20220919-WA0005~2.jpg", width: null, height: null },
  { id: generateId(), url: "https://www.elbutanero.com/content/uploads/images/October2022/IMG-20221012-WA0003.jpg", width: null, height: null },
  { id: generateId(), url: "https://www.elbutanero.com/content/uploads/images/June2022/electricista.jpg", width: null, height: null },
  { id: generateId(), url: "https://www.elbutanero.com/content/uploads/images/June2022/FB_IMG_1656087685297.jpg", width: null, height: null },
  { id: generateId(), url: "https://www.elbutanero.com/content/uploads/images/June2022/perro-hombre.jpg", width: null, height: null },
  { id: generateId(), url: "https://www.elbutanero.com/content/uploads/images/May2022/IMG-20220512-WA0012.jpg", width: null, height: null },
  { id: generateId(), url: "https://www.elbutanero.com/content/uploads/images/May2022/IMG-20220512-WA0012.jpg", width: null, height: null },
  { id: generateId(), url: "https://www.elbutanero.com/content/uploads/images/February2022/republica-checa-ucrania.jpg", width: null, height: null },
  { id: generateId(), url: "https://www.elbutanero.com/content/uploads/images/February2022/rusia-vs-ucrania.jpg", width: null, height: null },
  { id: generateId(), url: "https://www.elbutanero.com/content/uploads/images/February2022/lotr-ucrania.jpg", width: null, height: null },
  { id: generateId(), url: "https://www.elbutanero.com/content/uploads/images/January2022/Screenshot_20220122-141321.png", width: null, height: null },
  { id: generateId(), url: "https://www.elbutanero.com/content/uploads/images/January2022/IMG-20220101-WA0006.jpg", width: null, height: null },
  { id: generateId(), url: "https://www.elbutanero.com/content/uploads/images/January2022/IMG-20220103-WA0015.jpg", width: null, height: null },
  { id: generateId(), url: "https://statics.memondo.com/p/99/ccs/2025/05/CC_2818056_e15e064cfab346d2aa9967387c84ab1e_meme_otros_spiderman_en_las_americas.jpg?cb=8676898", width: null, height: null }, // Limpiar ?cb= si no es necesario
  { id: generateId(), url: "https://statics.memondo.com/p/99/ccs/2025/05/CC_2818190_0fb5644e3d7040dabe3851d5adb9f85d_otros_jamas_se_lo_perdonare.jpg?cb=2039822", width: null, height: null },
  { id: generateId(), url: "https://statics.memondo.com/p/99/ccs/2025/05/CC_2818138_d5914da2fb7c4dc5bbf08dd7d50f6389_meme_otros_tiempo_extra.jpg?cb=3964388", width: null, height: null },
  { id: generateId(), url: "https://statics.memondo.com/p/99/ccs/2025/05/CC_2818064_b3bbff9b7b1943fdae8be1ecdc29bf0f_meme_otros_algo_hay_ahi.jpg?cb=5437622", width: null, height: null },
  { id: generateId(), url: "https://statics.memondo.com/p/99/ccs/2025/05/CC_2818189_2ac9fde160174a2f8950427d67ba74ef_otros_no_me_va_a_hacer_ningun_bien.jpg?cb=7734277", width: null, height: null },
  { id: generateId(), url: "https://preview.redd.it/when-you-didnt-read-the-fine-print-v0-8rp4vewida4f1.png?width=1080&crop=smart&auto=webp&s=570721e7d86cd3be5b7996fda7f9aaac51b30419", width: null, height: null }, // Limpiar parámetros de URL si es posible/necesario
  { id: generateId(), url: "https://preview.redd.it/no-i-wont-buy-your-stuff-v0-mss63s9xta4f1.jpeg?width=1080&crop=smart&auto=webp&s=c71ff61c782b9245bda25faba246dc02b8fb3606", width: null, height: null },
  { id: generateId(), url: "https://preview.redd.it/1e32x0oyhi2f1.png?width=320&crop=smart&auto=webp&s=0bda11bc08937c7f431cdb1d4e0adbf461eb0c57", width: null, height: null },
  { id: generateId(), url: "https://preview.redd.it/because-i-dont-like-it-v0-obo2umfgp84f1.jpeg?width=1080&crop=smart&auto=webp&s=58f28247e94b1ea19a973503d2e1ab2c13575efe", width: null, height: null },
  { id: generateId(), url: "https://preview.redd.it/checkpoint-found-v0-xz7fetb02e4f1.jpeg?width=640&crop=smart&auto=webp&s=10f49d8cc989865cb39e5c6f0fdd844a2667a62b", width: null, height: null },
  { id: generateId(), url: "https://preview.redd.it/byit66drsa4f1.gif?width=360&format=mp4&s=9ece3435caba7da0c20d5ec0e34664f1d0066cf2", width: null, height: null }, // Esta es un GIF/MP4, asegúrate que el cliente lo maneje
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED266/683c9ebe8cc2b.webp", width: null, height: null },
  { id: generateId(), url: "https://images7.memedroid.com/images/UPLOADED817/683c2a56183b5.webp", width: null, height: null },
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED266/683c9ebe8cc2b.webp", width: null, height: null },
  { id: generateId(), url: "https://images7.memedroid.com/images/UPLOADED530/683c89d598b85.webp", width: null, height: null },
  { id: generateId(), url: "https://images7.memedroid.com/images/UPLOADED408/683c0f7012fc7.webp", width: null, height: null },
  { id: generateId(), url: "https://images7.memedroid.com/images/UPLOADED414/683cb02fb4bcf.webp", width: null, height: null },
  { id: generateId(), url: "https://images7.memedroid.com/images/UPLOADED729/683cb92b05ef9.webp", width: null, height: null },
  { id: generateId(), url: "https://images7.memedroid.com/images/UPLOADED655/683cb1901bf81.webp", width: null, height: null },
  { id: generateId(), url: "https://images7.memedroid.com/images/UPLOADED370/683ccbb44751b.webp", width: null, height: null },
  { id: generateId(), url: "https://images7.memedroid.com/images/UPLOADED475/683cbdffe68b1.webp", width: null, height: null },
  { id: generateId(), url: "https://images7.memedroid.com/images/UPLOADED988/683c67cedae47.webp", width: null, height: null },
  { id: generateId(), url: "https://images7.memedroid.com/images/UPLOADED475/683cbdffe68b1.webp", width: null, height: null },
  { id: generateId(), url: "https://images7.memedroid.com/images/UPLOADED475/683cbdffe68b1.webp", width: null, height: null },
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED394/683c97deadbe5.webp", width: null, height: null },
  { id: generateId(), url: "https://images7.memedroid.com/images/UPLOADED670/683c96ffd7ba8.webp", width: null, height: null },
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED226/683c8969c9e99.webp", width: null, height: null },
  { id: generateId(), url: "https://images7.memedroid.com/images/UPLOADED877/683c88212b128.webp", width: null, height: null },
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED820/683c941b12e71.webp", width: null, height: null },
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED308/683cab8a5bc14.webp", width: null, height: null },
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED913/683c9d619d302.webp", width: null, height: null },
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED464/683c98059b756.webp", width: null, height: null },
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED464/683c98059b756.webp", width: null, height: null },
  { id: generateId(), url: "https://rvideos2.memedroid.com/videos/UPLOADED985/683ca68590ad7.mp4", width: null, height: null },
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED653/683c7f10d8381.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED331/683c7cd43b8f6.jpeg", width: null, height: null },
  { id: generateId(), url: "https://rvideos2.memedroid.com/videos/UPLOADED961/683c7fcae340e.mp4", width: null, height: null },
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED633/683c7f31d997c.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED986/683c7ceeda90c.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images7.memedroid.com/images/UPLOADED370/683c74da3090e.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED237/683c7ac62cffc.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images7.memedroid.com/images/UPLOADED223/683c7d10acdd9.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED952/683c767834d0d.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED92/683c7ee60463e.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images7.memedroid.com/images/UPLOADED331/683c7ce066db2.jpeg", width: null, height: null },
  { id: generateId(), url: "https://rvideos2.memedroid.com/videos/UPLOADED985/683ca68590ad7.mp4", width: null, height: null },
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED653/683c7f10d8381.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED331/683c7cd43b8f6.jpeg", width: null, height: null },
  { id: generateId(), url: "https://rvideos2.memedroid.com/videos/UPLOADED961/683c7fcae340e.mp4", width: null, height: null },
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED633/683c7f31d997c.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED986/683c7ceeda90c.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images7.memedroid.com/images/UPLOADED370/683c74da3090e.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED237/683c7ac62cffc.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images7.memedroid.com/images/UPLOADED223/683c7d10acdd9.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED952/683c767834d0d.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED92/683c7ee60463e.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images7.memedroid.com/images/UPLOADED331/683c7ce066db2.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED308/683cab8a5bc14.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images7.memedroid.com/images/UPLOADED414/683cb02fb4bcf.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images7.memedroid.com/images/UPLOADED643/683cb024a37c3.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images7.memedroid.com/images/UPLOADED831/683cb011ec335.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images7.memedroid.com/images/UPLOADED823/683c8ab01a08b.jpeg", width: null, height: null },
  { id: generateId(), url: "https://rvideos2.memedroid.com/videos/UPLOADED869/683c872eaaa56.mp4", width: null, height: null },
  { id: generateId(), url: "https://images7.memedroid.com/images/UPLOADED475/683cbdffe68b1.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images7.memedroid.com/images/UPLOADED687/683cb1d2bcc10.jpeg", width: null, height: null },
  { id: generateId(), url: "https://rvideos2.memedroid.com/videos/UPLOADED669/683cae779719b.mp4", width: null, height: null },
  { id: generateId(), url: "https://rvideos2.memedroid.com/videos/UPLOADED710/683ca824844a3.mp4", width: null, height: null },
  { id: generateId(), url: "https://rvideos2.memedroid.com/videos/UPLOADED851/683c7a046aadb.mp4", width: null, height: null },
  { id: generateId(), url: "https://images7.memedroid.com/images/UPLOADED988/683c67cedae47.jpeg", width: null, height: null },
  { id: generateId(), url: "https://rvideos1.memedroid.com/videos/UPLOADED518/683c8214e7874.mp4", width: null, height: null },
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED95/683cb93965030.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED965/683cb234ead37.jpeg", width: null, height: null },
  { id: generateId(), url: "https://rvideos2.memedroid.com/videos/UPLOADED707/683c15d6bf27e.mp4", width: null, height: null },
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED394/683c97deadbe5.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images7.memedroid.com/images/UPLOADED670/683c96ffd7ba8.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED226/683c8969c9e99.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images7.memedroid.com/images/UPLOADED877/683c88212b128.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED820/683c941b12e71.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images7.memedroid.com/images/UPLOADED523/683c8b2cb5462.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED847/683c88fd166f5.jpeg", width: null, height: null },
  { id: generateId(), url: "https://rvideos1.memedroid.com/videos/UPLOADED897/683ca6510fa3e.mp4", width: null, height: null },
  { id: generateId(), url: "https://images7.memedroid.com/images/UPLOADED953/683cb02148e7c.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED966/683cb2ec10ea6.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED464/683c98059b756.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images3.memedroid.com/images/UPLOADED913/683c9d619d302.jpeg", width: null, height: null },
  { id: generateId(), url: "https://images7.memedroid.com/images/UPLOADED362/683c97f851820.jpeg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/30b1gx.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/1g8my4.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/1ur9b0.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/3lmzyx.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/22bdq6.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/3oevdk.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/261o3j.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/23ls.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/2fm6x.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/26jxvz.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/28j0te.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/1c1uej.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/46e43q.png", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/24y43o.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/9ehk.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/5c7lwq.png", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/43a45p.png", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/345v97.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/1otk96.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/1ihzfe.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/1jwhww.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/54hjww.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/2ybua0.png", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/1tl71a.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/1b42wl.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/2odckz.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/1bij.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/1o00in.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/2gnnjh.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/1bhk.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/2za3u1.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/46hhvr.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/wxica.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/1wz1x.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/gk5el.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/26am.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/21uy0f.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/m78d.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/gtj5t.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/3pdf2w.png", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/1w7ygt.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/72epa9.png", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/64sz4u.png", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/38el31.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/1ii4oc.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/1ii4oc.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/2xscjb.png", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/1e7ql7.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/1h7in3.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/1yxkcp.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/145qvv.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/2reqtg.png", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/3qqcim.png", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/5v6gwj.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/58eyvu.png", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/4pn1an.png", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/1nck6k.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/98qr33.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/2kbn1e.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/1yz6z4.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/265k.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/39t1o.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/2tzo2k.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/1op9wy.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/8k0sa.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/28s2gu.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/3vfrmx.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/3eqjd8.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/1bgw.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/434i5j.png", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/3nx72a.png", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/1bhw.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/8tw3vb.png", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/33e92f.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/3po4m7.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/4acd7j.png", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/u0pf0.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/19vcz0.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/3kwur5.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/21tqf4.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/grr.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/2896ro.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/65939r.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/2oo7h0.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/29v4rt.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/392xtu.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/9tpn17.png", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/3pnmg.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/hmt3v.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/2wifvo.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/54d9lj.png", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/2cjr7j.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/3gdsh1.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/1bh8.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/1tkjq9.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/5o32tt.png", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/5youx3.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/bwu6w.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/24zoa8.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/176h0h.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.imgflip.com/1itoun.jpg", width: null, height: null },
  { id: generateId(), url: "https://i.redd.it/8gl88ceiwe4f1.jpeg", width: null, height: null },
  { id: generateId(), url: "https://i.redd.it/g95otjdgsc4f1.png", width: null, height: null },
  { id: generateId(), url: "https://i.redd.it/8rp4vewida4f1.png", width: null, height: null },
  { id: generateId(), url: "https://i.redd.it/zw3cr55smd4f1.jpeg", width: null, height: null },
  { id: generateId(), url: "https://i.redd.it/mss63s9xta4f1.jpeg", width: null, height: null },
  { id: generateId(), url: "https://i.redd.it/olnln7f60d4f1.jpeg", width: null, height: null },
  { id: generateId(), url: "https://i.redd.it/mh3fqtcdbd4f1.jpeg", width: null, height: null },
  { id: generateId(), url: "https://i.redd.it/7vzo9tqv9a4f1.gif", width: null, height: null },
  { id: generateId(), url: "https://i.redd.it/dfus61xvza4f1.jpeg", width: null, height: null },
  { id: generateId(), url: "https://i.redd.it/xu2eqrhp2f4f1.jpeg", width: null, height: null },
  { id: generateId(), url: "https://i.redd.it/7vzo9tqv9a4f1.gif", width: null, height: null },
  { id: generateId(), url: "https://i.redd.it/7lw32ob0la4f1.jpeg", width: null, height: null },
  { id: generateId(), url: "https://i.redd.it/oc6vokwja84f1.gif", width: null, height: null },
  { id: generateId(), url: "https://i.redd.it/xz7fetb02e4f1.jpeg", width: null, height: null },
  { id: generateId(), url: "https://i.redd.it/obo2umfgp84f1.jpeg", width: null, height: null },
  { id: generateId(), url: "https://i.redd.it/2ff85x1gge4f1.jpeg", width: null, height: null },
  { id: generateId(), url: "https://i.redd.it/sjtvuzpubd4f1.jpeg", width: null, height: null },
  { id: generateId(), url: "https://i.redd.it/ack6k3ww7c4f1.gif", width: null, height: null },
  { id: generateId(), url: "https://i.redd.it/xcdtp1c79d4f1.jpeg", width: null, height: null },
  { id: generateId(), url: "https://i.redd.it/k9kymht03e4f1.jpeg", width: null, height: null },
  { id: generateId(), url: "https://i.redd.it/kyqov9245b4f1.gif", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/kH6o0mN.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/vTSZ6CG.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/hGED0m9.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/SjnMMhd.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/rdw32yx.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/xHcS2LF.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/DRd0yKE.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/t9uwvai.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/kBSZgbG.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/CATjyHj.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/8Tkr6ld.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/ZaSaYAK.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/CFLPW9U.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/NImikb7.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/4L89AMP.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/NyEoz2g.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/Cq6w7Rd.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/WMgvwaq.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/iN5P0r4.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/JqhcMU4.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/U9GK6jL.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/wJUtNXR.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/6otWkQZ.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/bxMhEKZ.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/MhbPTSQ.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/X6niVYQ.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/CD0nLh8.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/sV4AReH.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/EFHsGkJ.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/gXmsig6.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/Bp2y4zT.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/HdmBrwX.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/Mgyz87x.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/PFzOfO7.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/rxlv8TX.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/0JmUzko.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/gEZW60M.png", width: null, height: null },
  { id: generateId(), url: "http://imgur.com/uXKy3RJ.png", width: null, height: null },
  { id: generateId(), url: "https://static.bitrue.com/bitrue-cms/upload/All_Brainrot_Characters_Name_Story_and_Image_e345b6e628.png", width: null, height: null },
  { id: generateId(), url: "https://static.bitrue.com/bitrue-cms/upload/register_banner_bitrue_91c17ab0da.jpg", width: null, height: null },
  { id: generateId(), url: "https://static.bitrue.com/bitrue-cms/upload/6a32b_17450654163973_49199fefb8.jpg", width: null, height: null },
  { id: generateId(), url: "https://static.bitrue.com/bitrue-cms/upload/0516c_17450652924695_jpg_dada18f400.webp", width: null, height: null },
  { id: generateId(), url: "https://static.bitrue.com/bitrue-cms/upload/3a697_17450657256122_68f695ad2e.jpg", width: null, height: null },
  { id: generateId(), url: "https://static.bitrue.com/bitrue-cms/upload/2b6d4_17450660238237_34f5f1957a.jpg", width: null, height: null },
  { id: generateId(), url: "https://static.bitrue.com/bitrue-cms/upload/11f97_17450661838357_jpg_02f8bec121.webp", width: null, height: null },
  { id: generateId(), url: "https://static.bitrue.com/bitrue-cms/upload/d3eb9_17450664416698_100ca0d35c.jpg", width: null, height: null },
    ];

    if (pathname === "/api/imagen-aleatoria") {
      const random = imagesData[Math.floor(Math.random() * imagesData.length)];
      return new Response(JSON.stringify([random]), {
        headers: {
          "Content-Type": "application/json",
          "Access-Control-Allow-Origin": "*"
        }
      });
    }

    return new Response(
      "¡API de imágenes funcionando! Usa /api/imagen-aleatoria",
      {
        headers: {
          "Content-Type": "text/plain",
          "Access-Control-Allow-Origin": "*"
        }
      }
    );
  }
};
